name: Main workflow runs from Main branch

on:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout to main branch
        uses: actions/checkout@v4

      - name: list files
        run: ls -al

      - name: Execute hello-world shell script from Main branch
        run: sh shell-scripts/hello-world.sh 